IOC_TOP = /reg/g/pcds/epics/R7.0.2-2.0/ioc/ads-ioc/v0.0.2
IOC_INSTANCE_PATH := $(shell pwd)

PROJECT_NAME = HOMS_Test
PROJECT_PATH := ../../HOMS_Test.tsproj
PLC = HOMS_Test_PLC

PYTMC_OPTS = 
PREFIX = PREFIX:

include $(IOC_TOP)/iocBoot/templates/Makefile.base
